// All States of America
export const USState = [
  {label: 'Iowa', value: 'iowa'},
  {label: 'New York', value: 'newyork'},
  {label: 'Alabama', value: 'alabama'},
  {label: 'Alaska', value: 'alaska'},
  {label: 'Arizona', value: 'arizona'},
  {label: 'Arkansas', value: 'arkansas'},
  {label: 'California', value: 'california'},
  {label: 'Colorado', value: 'colorado'},
  {label: 'Connecticut', value: 'connecticut'},
  {label: 'Delaware', value: 'delaware'},
  {label: 'Florida', value: 'florida'},
  {label: 'Georgia', value: 'georgia'},
  {label: 'Hawaii', value: 'hawaii'},
  {label: 'Idaho', value: 'idaho'},
  {label: 'Illinois', value: 'illinois'},
  {label: 'Indiana', value: 'indiana'},
  {label: 'Kansas', value: 'kansas'},
  {label: 'Kentucky', value: 'kentucky'},
  {label: 'Louisiana', value: 'louisiana'},
  {label: 'Maine', value: 'maine'},
  {label: 'Maryland', value: 'maryland'},
  {label: 'Massachusetts', value: 'massachusetts'},
  {label: 'Michigan', value: 'michigan'},
  {label: 'Minnesota', value: 'minnesota'},
  {label: 'Mississippi', value: 'mississippi'},
  {label: 'Missouri', value: 'missouri'},
  {label: 'Montana', value: 'montana'},
  {label: 'Nebraska', value: 'nebraska'},
  {label: 'Nevada', value: 'nevada'},
  {label: 'New Hampshire', value: 'newhampshire'},
  {label: 'New Jersey', value: 'newjersey'},
  {label: 'New Mexico', value: 'newmexico'},
  {label: 'North Carolina', value: 'northcarolina'},
  {label: 'North Dakota', value: 'northdakota'},
  {label: 'Ohio', value: 'ohio'},
  {label: 'Oklahoma', value: 'oklahoma'},
  {label: 'Oregon', value: 'oregon'},
  {label: 'Pennsylvania', value: 'pennsylvania'},
  {label: 'Rhode Island', value: 'rhodeisland'},
  {label: 'South Carolina', value: 'southcarolina'},
  {label: 'South Dakota', value: 'southdakota'},
  {label: 'Tennessee', value: 'tennessee'},
  {label: 'Texas', value: 'texas'},
  {label: 'Utah', value: 'utah'},
  {label: 'Vermont', value: 'vermont'},
  {label: 'Virginia', value: 'virginia'},
  {label: 'Washington', value: 'washington'},
  {label: 'West Virginia', value: 'westvirginia'},
  {label: 'Wisconsin', value: 'wisconsin'},
  {label: 'Wyoming', value: 'wyoming'},
];

// List of Australia's States
export const australiaState = [
  {
    label: 'Australian Capital Territory',
    value: 'australiancapitalterritory',
  },
  {label: 'New South Wales', value: 'newsouthwales'},
  {label: 'Northern Territory', value: 'northernterritory'},
  {label: 'Queensland', value: 'queensland'},
  {label: 'South Australia', value: 'southaustralia'},
  {label: 'Tasmania', value: 'tasmania'},
  {label: 'Victoria', value: 'victoria'},
  {label: 'Western Australia', value: 'westernaustralia'},
];

// List of Canada's States
export const canadaStates = [
  {label: 'Alberta', value: 'alberta'},
  {label: 'British Columbia', value: 'britishcolumbia'},
  {label: 'Manitoba', value: 'manitoba'},
  {label: 'New Brunswick', value: 'newbrunswick'},
  {label: 'Newfoundland and Labrador', value: 'newfoundlandandlabrador'},
  {label: 'Northwest Territories', value: 'northwestterritories'},
  {label: 'Nova Scotia', value: 'novascotia'},
  {label: 'Nunavut', value: 'nunavut'},
  {label: 'Ontario', value: 'ontario'},
  {label: 'Prince Edward Island', value: 'princeedwardisland'},
  {label: 'Quebec', value: 'quebec'},
  {label: 'Saskatchewan', value: 'saskatchewan'},
  {label: 'Yukon', value: 'yukon'},
];

// List of United Kingdom's States
export const UKStates = [
  {label: 'England', value: 'england'},
  {label: 'Scotland', value: 'scotland'},
  {label: 'Wales', value: 'wales'},
  {label: 'Northern Ireland', value: 'northernireland'},
];

// List of NewZealand States
export const NewZealandStates = [
  {label: 'Auckland', value: 'auckland'},
  {label: 'Bay of Plenty', value: 'bayofplenty'},
  {label: 'Canterbury', value: 'canterbury'},
  {label: 'Chatham Islands Territory', value: 'chathamislandsterritory'},
  {label: 'Gisborne', value: 'gisborne'},
  {label: "Hawke's Bay", value: 'hawkesbay'},
  {label: 'Manawatu-Wanganui', value: 'manawatuwanganui'},
  {label: 'Marlborough', value: 'marlborough'},
  {label: 'Nelson', value: 'nelson'},
  {label: 'Northland', value: 'northland'},
  {label: 'Otago', value: 'otago'},
  {label: 'Southland', value: 'southland'},
  {label: 'Taranaki', value: 'taranaki'},
  {label: 'Tasman', value: 'tasman'},
  {label: 'Waikato', value: 'waikato'},
  {label: 'Wellington', value: 'wellington'},
  {label: 'West Coast', value: 'westcoast'},
];

export const genderList = [
  {value: 'MALE', label: 'Male'},
  {value: 'FEMALE', label: 'Female'},
  {value: 'OTHER', label: 'Other'},
  {value: 'DECLINE', label: 'Decline'},
];

export const dieses = [
  {
    label: 'ABCD Syndrome',
    value: 'ABCD Syndrome',
  },
  {
    label: 'Achalasia',
    value: 'Achalasia',
  },
  {
    label: 'Acoustic Neuroma (Vestibula Schwannoma)',
    value: 'Acoustic Neuroma (Vestibula Schwannoma)',
  },
  {
    label: 'Acromegaly',
    value: 'Acromegaly',
  },
  {
    label: 'Adams-Oliver Syndrome (AOS)',
    value: 'Adams-Oliver Syndrome (AOS)',
  },
  {
    label: 'Addiction',
    value: 'Addiction',
  },
  {
    label: "Addison's Disease (Adrenal insufficiency)",
    value: "Addison's Disease (Adrenal insufficiency)",
  },
  {
    label: 'Adenomyosis',
    value: 'Adenomyosis',
  },
  {
    label: 'Adhesive Capsulitis (Frozen Shoulder)',
    value: 'Adhesive Capsulitis (Frozen Shoulder)',
  },
  {
    label: 'Adrenal Cortical Carcinoma (ACC)',
    value: 'Adrenal Cortical Carcinoma (ACC)',
  },
  {
    label: 'Agenesis of the Corpus Callosum (ACC)',
    value: 'Agenesis of the Corpus Callosum (ACC)',
  },
  {
    label: 'Aicardi Syndrome',
    value: 'Aicardi Syndrome',
  },
  {
    label: 'Alagille Syndrome (AS)',
    value: 'Alagille Syndrome (AS)',
  },
  {
    label: 'Albinism',
    value: 'Albinism',
  },
  {
    label: 'Alkaptonuria',
    value: 'Alkaptonuria',
  },
  {
    label: 'Allergies',
    value: 'Allergies',
  },
  {
    label: 'Alopecia',
    value: 'Alopecia',
  },
  {
    label: 'Alpha 1 Antitrypsin Deficiency (A1AD)',
    value: 'Alpha 1 Antitrypsin Deficiency (A1AD)',
  },
  {
    label: 'Alternating Hemiplegia of Childhood (AHC)',
    value: 'Alternating Hemiplegia of Childhood (AHC)',
  },
  {
    label: "Alzheimer's Disease (AD)",
    value: "Alzheimer's Disease (AD)",
  },
  {
    label: 'Amniotic Band Syndrome',
    value: 'Amniotic Band Syndrome',
  },
  {
    label: 'Amplified Musculoskeletal Pain Syndrome',
    value: 'Amplified Musculoskeletal Pain Syndrome',
  },
  {
    label: 'Amputation',
    value: 'Amputation',
  },
  {
    label: 'Amyloidosis',
    value: 'Amyloidosis',
  },
  {
    label: 'Amyotrophic Lateral Sclerosis (ALS)',
    value: 'Amyotrophic Lateral Sclerosis (ALS)',
  },
  {
    label: 'Anal Cancer',
    value: 'Anal Cancer',
  },
  {
    label: 'Aneurysm',
    value: 'Aneurysm',
  },
  {
    label: 'Anhidrosis (Hypohydrosis)',
    value: 'Anhidrosis (Hypohydrosis)',
  },
  {
    label: 'Ankylosing Spondylitis (AS)',
    value: 'Ankylosing Spondylitis (AS)',
  },
  {
    label: 'Anoxic Brain Injury',
    value: 'Anoxic Brain Injury',
  },
  {
    label: 'Anosmia (loss of smell)',
    value: 'Anosmia (loss of smell)',
  },
  {
    label: 'Antiphospholipid Syndrome (APS)',
    value: 'Antiphospholipid Syndrome (APS)',
  },
  {
    label: 'Antisynthetase Syndrome',
    value: 'Antisynthetase Syndrome',
  },
  {
    label: 'Anxiety',
    value: 'Anxiety',
  },
  {
    label: 'Aortic Disease',
    value: 'Aortic Disease',
  },
  {value: 'Aphantasia', label: 'Aphantasia'},
  {value: 'Aphasia', label: 'Aphasia'},
  {value: 'Aplastic Anemia (AA)', label: 'Aplastic Anemia (AA)'},
  {value: 'Appendix Cancer', label: 'Appendix Cancer'},
  {value: 'Apraxia', label: 'Apraxia'},
  {value: 'Arachnoid Cyst', label: 'Arachnoid Cyst'},
  {value: 'Arachnoiditis', label: 'Arachnoiditis'},
  {
    value: 'Arteriovenous Malformation (AVM)',
    label: 'Arteriovenous Malformation (AVM)',
  },
  {
    value: 'Arthrogryposis Multiplex Congenita (AMC)',
    label: 'Arthrogryposis Multiplex Congenita (AMC)',
  },
  {value: 'Aspirin-like defect (ALD)', label: 'Aspirin-like defect (ALD)'},
  {value: 'Asthma', label: 'Asthma'},
  {value: 'Ataxia', label: 'Ataxia'},
  {value: 'Atrial Fibrillation (AFIB)', label: 'Atrial Fibrillation (AFIB)'},
  {value: 'Atrophic Vaginitis', label: 'Atrophic Vaginitis'},
  {
    value: 'Attention Deficit Hyperactivity Disorder (ADH, ADD)',
    label: 'Attention Deficit Hyperactivity Disorder (ADH, ADD)',
  },
  {
    value: 'Atypical Hemolytic Uremic Syndrome (aHUS)',
    label: 'Atypical Hemolytic Uremic Syndrome (aHUS)',
  },
  {
    value: 'Auditory Processing Disorder (APD)',
    label: 'Auditory Processing Disorder (APD)',
  },
  {value: 'Autism', label: 'Autism'},
  {value: 'Autoimmune Disease', label: 'Autoimmune Disease'},
  {
    value: 'Autoimmune Encephalitis (AE)',
    label: 'Autoimmune Encephalitis (AE)',
  },
  {
    value: 'Avascular Necrosis (AV, Osteonecrosis)',
    label: 'Avascular Necrosis (AV, Osteonecrosis)',
  },
  {value: "Barrett's Esophagus", label: "Barrett's Esophagus"},
  {value: 'Barth Syndrome (BTHS)', label: 'Barth Syndrome (BTHS)'},
  {value: 'Bartonella', label: 'Bartonella'},
  {value: 'Basal Cell Carcinoma (BCC)', label: 'Basal Cell Carcinoma (BCC)'},
  {value: 'Batten Disease', label: 'Batten Disease'},
  {
    value: 'Beckwith-Wiedemann Syndrome (BWS)',
    label: 'Beckwith-Wiedemann Syndrome (BWS)',
  },
  {value: "Behcet's Disease (BD)", label: "Behcet's Disease (BD)"},
  {value: "Bell's Palsy", label: "Bell's Palsy"},
  {
    value: 'Benign Prostatic Hyperplasia (BP, Enlarged Prostate)',
    label: 'Benign Prostatic Hyperplasia (BP, Enlarged Prostate)',
  },
  {
    value: 'Beta Thalassemia (Cooley s Anemia)',
    label: 'Beta Thalassemia (Cooley s Anemia)',
  },
  {
    value: 'Bile Acid Malabsorption (BAD)',
    label: 'Bile Acid Malabsorption (BAD)',
  },
  {
    value: 'Bile Duct Cancer (Cholangiocarcinoma)',
    label: 'Bile Duct Cancer (Cholangiocarcinoma)',
  },
  {value: 'Bipolar', label: 'Bipolar'},
  {value: 'Bladder Cancer', label: 'Bladder Cancer'},
  {value: 'Blood Cancer', label: 'Blood Cancer'},
  {value: 'Blood Clot', label: 'Blood Clot'},
  {value: 'Blood Clotting Disorder', label: 'Blood Clotting Disorder'},
  {value: "Blount's Disease", label: "Blount's Disease"},
  {value: 'Bone Cancer', label: 'Bone Cancer'},
  {
    value: 'Borderline Personality Disorder (BPD)',
    label: 'Borderline Personality Disorder (BPD)',
  },
  {value: 'Brain Aneurysm', label: 'Brain Aneurysm'},
  {value: 'Brain Cancer', label: 'Brain Cancer'},
  {value: 'Brain Damage', label: 'Brain Damage'},
  {value: 'Brain Tumor', label: 'Brain Tumor'},
  {value: 'BRCA Mutation', label: 'BRCA Mutation'},
  {value: 'Breast Cancer (BC)', label: 'Breast Cancer (BC)'},
  {value: 'Breast Cancer in Men', label: 'Breast Cancer in Men'},
  {value: 'Breast Implant Illness', label: 'Breast Implant Illness'},
  {value: 'Bronchiectasis', label: 'Bronchiectasis'},
  {value: 'Bronchitis', label: 'Bronchitis'},
  {
    value: 'Bronchopulmonary Dysplasia (BPD)',
    label: 'Bronchopulmonary Dysplasia (BPD)',
  },
  {value: 'Bulging Disc', label: 'Bulging Disc'},
  {value: 'Bursitis', label: 'Bursitis'},
  {value: 'Calcinosis', label: 'Calcinosis'},
  {value: 'Calciphylaxis', label: 'Calciphylaxis'},
  {value: 'Campomelic Dysplasia', label: 'Campomelic Dysplasia'},
  {value: 'Cancer', label: 'Cancer'},
  {
    value: 'Candidiasis (Yeast Infection)',
    label: 'Candidiasis (Yeast Infection)',
  },
  {
    value: 'Capillary Lymphatic Venous Malformations (CLVMs)',
    label: 'Capillary Lymphatic Venous Malformations (CLVMs)',
  },
  {value: 'Carcinoid Cancer', label: 'Carcinoid Cancer'},
  {value: 'Carcinoma', label: 'Carcinoma'},
  {
    value: 'Cardiofaciocutaneous Syndrome (CFC syndrome)',
    label: 'Cardiofaciocutaneous Syndrome (CFC syndrome)',
  },
  {value: 'Carnitine Deficiency', label: 'Carnitine Deficiency'},
  {value: 'Caroli Disease', label: 'Caroli Disease'},
  {
    value: 'Carpal Tunnel Syndrome (CTS)',
    label: 'Carpal Tunnel Syndrome (CTS)',
  },
  {value: 'Castleman Disease (CD)', label: 'Castleman Disease (CD)'},
  {value: 'Catheter', label: 'Catheter'},
  {value: 'Cauda Equina Syndrome', label: 'Cauda Equina Syndrome'},
  {value: 'Celiac Disease (CCD)', label: 'Celiac Disease (CCD)'},
  {value: 'Cellulitis', label: 'Cellulitis'},
  {value: 'Central Pain Syndrome (CPS)', label: 'Central Pain Syndrome (CPS)'},
  {value: 'Cerebellar Atrophy', label: 'Cerebellar Atrophy'},
  {value: 'Cerebral Amyloid Angiopathy', label: 'Cerebral Amyloid Angiopathy'},
  {
    value: 'Cerebral Cavernous Malformations (CCMs)',
    label: 'Cerebral Cavernous Malformations (CCMs)',
  },
  {value: 'Cerebral Palsy (CP)', label: 'Cerebral Palsy (CP)'},
  {value: 'Cervical Cancer', label: 'Cervical Cancer'},
  {value: 'Cervical Dystonia', label: 'Cervical Dystonia'},
  {value: 'Charge Syndrome', label: 'Charge Syndrome'},
  {value: 'Chiari Malformation (CM)', label: 'Chiari Malformation (CM)'},
  {value: 'Chilblains (Pernio)', label: 'Chilblains (Pernio)'},
  {
    value: 'Chronic Fatigue Syndrome (CF, ME)',
    label: 'Chronic Fatigue Syndrome (CF, ME)',
  },
  {
    value: 'Chronic Inflammatory Demyelinating Polyneuropathy (CIDP)',
    label: 'Chronic Inflammatory Demyelinating Polyneuropathy (CIDP)',
  },
  {
    value: 'Chronic Intestinal Pseudo-obstruction (CIPO)',
    label: 'Chronic Intestinal Pseudo-obstruction (CIPO)',
  },
  {
    value: 'Chronic obstructive pulmonary disease (COPD)',
    label: 'Chronic obstructive pulmonary disease (COPD)',
  },
  {value: 'Chronic Pain', label: 'Chronic Pain'},
  {
    value: 'Chronic Venous Insufficiency (CVI)',
    label: 'Chronic Venous Insufficiency (CVI)',
  },
  {value: 'Cleft', label: 'Cleft'},
  {
    value: 'Clostridium difficile (C Diff)',
    label: 'Clostridium difficile (C Diff)',
  },
  {value: 'Clubfoot', label: 'Clubfoot'},
  {value: 'Cluster Headache', label: 'Cluster Headache'},
  {value: 'Coffin-Lowry Syndrome (CLS)', label: 'Coffin-Lowry Syndrome (CLS)'},
  {value: 'Cognitive Impairment (CI)', label: 'Cognitive Impairment (CI)'},
  {value: 'Colon Polyps', label: 'Colon Polyps'},
  {value: 'Colonic Inertia', label: 'Colonic Inertia'},
  {value: 'Color Blind', label: 'Color Blind'},
  {value: 'Colorectal (Colon) Cancer', label: 'Colorectal (Colon) Cancer'},
  {
    value: 'Complex Regional Pain Syndrome (CRP, RSD)',
    label: 'Complex Regional Pain Syndrome (CRP, RSD)',
  },
  {
    value: 'Congenital Adrenal Hyperplasia (CAH)',
    label: 'Congenital Adrenal Hyperplasia (CAH)',
  },
  {
    value: 'Congenital Central Hypoventilation Syndrome (CCHS)',
    label: 'Congenital Central Hypoventilation Syndrome (CCHS)',
  },
  {value: 'Congenital Myopathy', label: 'Congenital Myopathy'},
  {
    value: 'Congenital Sucrase-Isomaltase Deficiency (CSID)',
    label: 'Congenital Sucrase-Isomaltase Deficiency (CSID)',
  },
  {value: 'Constipation', label: 'Constipation'},
  {value: 'Conversion Disorder (CD)', label: 'Conversion Disorder (CD)'},
  {value: 'Coronavirus (COVID-19)', label: 'Coronavirus (COVID-19)'},
  {value: 'Cortical Dysplasia', label: 'Cortical Dysplasia'},
  {value: 'Costochondritis', label: 'Costochondritis'},
  {value: 'Cowden Syndrome (CS)', label: 'Cowden Syndrome (CS)'},
  {
    value: 'Craniocervical Instability (CCI)',
    label: 'Craniocervical Instability (CCI)',
  },
  {value: 'Craniosynostosis', label: 'Craniosynostosis'},
  {value: "Crohn's Disease (CD)", label: "Crohn's Disease (CD)"},
  {value: "Cushing's Disease (CS)", label: "Cushing's Disease (CS)"},
  {
    value: 'Cyclic Vomiting Syndrome (CVS)',
    label: 'Cyclic Vomiting Syndrome (CVS)',
  },
  {value: 'Cystic Fibrosis (CF)', label: 'Cystic Fibrosis (CF)'},
  {value: 'Cystic Hygroma', label: 'Cystic Hygroma'},
  {value: 'Cystinosis', label: 'Cystinosis'},
  {value: 'Cytomegalovirus (CMV)', label: 'Cytomegalovirus (CMV)'},
  {value: 'Dandy Walker Syndrome (DWS)', label: 'Dandy Walker Syndrome (DWS)'},
  {value: 'Danon Disease', label: 'Danon Disease'},
  {
    value: 'Darier Disease (DD Keratosis Follicularis)',
    label: 'Darier Disease (DD Keratosis Follicularis)',
  },
  {value: 'Deep Vein Thrombosis (DVT)', label: 'Deep Vein Thrombosis (DVT)'},
  {
    value: 'Degenerative Disc Disease (DDD)',
    label: 'Degenerative Disc Disease (DDD)',
  },
  {
    value: 'Deletion Duplication Syndrome',
    label: 'Deletion Duplication Syndrome',
  },
  {
    value: 'Delta-Storage Pool Deficiency',
    label: 'Delta-Storage Pool Deficiency',
  },
  {value: 'Depression (MDD)', label: 'Depression (MDD)'},
  {
    value: "Dercum's Disease (adiposis dolorosa)",
    label: "Dercum's Disease (adiposis dolorosa)",
  },
  {value: 'Dermatomyositis (DM)', label: 'Dermatomyositis (DM)'},
  {value: 'Desmoid Tumor', label: 'Desmoid Tumor'},
  {value: 'Developmental Delay (DD)', label: 'Developmental Delay (DD)'},
  {value: 'Diabetes (DM)', label: 'Diabetes (DM)'},
  {value: 'Disabled', label: 'Disabled'},
  {
    value: 'Disruptive Mood Dysregulation Disorder (DMDD)',
    label: 'Disruptive Mood Dysregulation Disorder (DMDD)',
  },
  {
    value: 'Dissociative Identity Disorder (DI, Multiple Personality Disorder)',
    label: 'Dissociative Identity Disorder (DI, Multiple Personality Disorder)',
  },
  {value: 'Diverticulitis', label: 'Diverticulitis'},
  {value: 'Down Syndrome (DS)', label: 'Down Syndrome (DS)'},
  {value: 'Dry Mouth', label: 'Dry Mouth'},
  {value: 'Duodenitis', label: 'Duodenitis'},
  {value: "Dupuytren's Contracture", label: "Dupuytren's Contracture"},
  {value: 'Dwarfism', label: 'Dwarfism'},
  {value: 'Dysarthria (Slurred Speech)', label: 'Dysarthria (Slurred Speech)'},
  {value: 'Dysautonomia', label: 'Dysautonomia'},
  {value: 'Dyskeratosis Congenita', label: 'Dyskeratosis Congenita'},
  {value: 'Dyslexia', label: 'Dyslexia'},
  {
    value: 'Dysmenorrhea (Painful Menstruation)',
    label: 'Dysmenorrhea (Painful Menstruation)',
  },
  {
    value: 'Dysphagia (Difficulty Swallowing)',
    label: 'Dysphagia (Difficulty Swallowing)',
  },
  {value: 'Dystonia', label: 'Dystonia'},
  {value: 'Ear Cancer', label: 'Ear Cancer'},
  {value: 'Eating Disorder', label: 'Eating Disorder'},
  {value: 'Eczema (Atopic Dermatitis)', label: 'Eczema (Atopic Dermatitis)'},
  {value: 'Edema', label: 'Edema'},
  {
    value: 'Ehlers-Danlos Syndrome (EDS)',
    label: 'Ehlers-Danlos Syndrome (EDS)',
  },
  {
    value: 'Elephantiasis (Lymphatic Filariasis)',
    label: 'Elephantiasis (Lymphatic Filariasis)',
  },
  {value: 'Empty Sella Syndrome (ESS)', label: 'Empty Sella Syndrome (ESS)'},
  {value: 'Encephalitis', label: 'Encephalitis'},
  {value: 'Encephalocele', label: 'Encephalocele'},
  {value: 'Endometrial Cancer', label: 'Endometrial Cancer'},
  {value: 'Endometriosis', label: 'Endometriosis'},
  {
    value: 'Enlarged Spleen (Splenomegaly)',
    label: 'Enlarged Spleen (Splenomegaly)',
  },
  {value: 'Eosinophilic Colitis (EC)', label: 'Eosinophilic Colitis (EC)'},
  {
    value: 'Eosinophilic Esophagitis (EOE)',
    label: 'Eosinophilic Esophagitis (EOE)',
  },
  {
    value: 'Eosinophilic Gasteroenteritis (EG)',
    label: 'Eosinophilic Gasteroenteritis (EG)',
  },
  {
    value: 'Epicondylitis (Tennis Elbow)',
    label: 'Epicondylitis (Tennis Elbow)',
  },
  {value: 'Epidermolysis Bullosa (EB)', label: 'Epidermolysis Bullosa (EB)'},
  {value: 'Epilepsy', label: 'Epilepsy'},
  {
    value: 'Epithelial Basement Membrane Dystrophy',
    label: 'Epithelial Basement Membrane Dystrophy',
  },
  {value: 'Epstein Barr Syndrome (EBV)', label: 'Epstein Barr Syndrome (EBV)'},
  {value: "Erb's Palsy", label: "Erb's Palsy"},
  {value: 'Erectile Dysfunction (ED)', label: 'Erectile Dysfunction (ED)'},
  {value: 'Erythema Nodosum', label: 'Erythema Nodosum'},
  {value: 'Erythromelalgia', label: 'Erythromelalgia'},
  {value: 'Esophageal Atresia (EA)', label: 'Esophageal Atresia (EA)'},
  {value: 'Esophageal Cancer', label: 'Esophageal Cancer'},
  {value: 'Esophageal Varices', label: 'Esophageal Varices'},
  {value: 'Essential Thrombocythemia', label: 'Essential Thrombocythemia'},
  {value: 'Essential Tremor', label: 'Essential Tremor'},
  {value: "Ewing's Sarcoma", label: "Ewing's Sarcoma"},
  {
    value: 'Exocrine Pancreatic Insufficiency (EPI)',
    label: 'Exocrine Pancreatic Insufficiency (EPI)',
  },
  {value: 'Eye Cancer', label: 'Eye Cancer'},
  {value: 'Fabry disease', label: 'Fabry disease'},
  {value: 'Failure to Thrive (FTT)', label: 'Failure to Thrive (FTT)'},
  {
    value: 'Familial Adenomatous Polyposis (FAP)',
    label: 'Familial Adenomatous Polyposis (FAP)',
  },
  {
    value: 'Familial Hypercholesterolemia (FH)',
    label: 'Familial Hypercholesterolemia (FH)',
  },
  {
    value: 'Familial Mediterranean Fever (FMF)',
    label: 'Familial Mediterranean Fever (FMF)',
  },
  {
    value: 'Fatty Oxidation Disorder (FAOD)',
    label: 'Fatty Oxidation Disorder (FAOD)',
  },
  {value: 'Feeding Tubes', label: 'Feeding Tubes'},
  {
    value: 'Fetal Alcohol Syndrome (FAS)',
    label: 'Fetal Alcohol Syndrome (FAS)',
  },
  {value: 'Fibrocystic Breasts', label: 'Fibrocystic Breasts'},
  {
    value: 'Fibrodysplasia Ossificans Progressiva (FOP)',
    label: 'Fibrodysplasia Ossificans Progressiva (FOP)',
  },
  {
    value: 'Fibromuscular Dysplasia (FMD)',
    label: 'Fibromuscular Dysplasia (FMD)',
  },
  {value: 'Fibromyalgia (FM)', label: 'Fibromyalgia (FM)'},
  {value: 'Fibrosing Mediastinitis', label: 'Fibrosing Mediastinitis'},
  {value: 'Fibrous Dysplasia', label: 'Fibrous Dysplasia'},
  {value: 'Fistula', label: 'Fistula'},
  {value: 'Foot Drop', label: 'Foot Drop'},
  {value: 'FOXG1 Syndrome', label: 'FOXG1 Syndrome'},
  {value: 'Fragile X Syndrome (FXS)', label: 'Fragile X Syndrome (FXS)'},
  {value: "Friedreich's Ataxia (FA)", label: "Friedreich's Ataxia (FA)"},
  {
    value: 'Functional Neurological Disorder (FND)',
    label: 'Functional Neurological Disorder (FND)',
  },
  {
    value: 'G6PD deficiency (glucose-6-phosphate-dehydrogenase deficiency)',
    label: 'G6PD deficiency (glucose-6-phosphate-dehydrogenase deficiency)',
  },
  {value: 'Galactosemia', label: 'Galactosemia'},
  {value: 'Gall Stones', label: 'Gall Stones'},
  {value: 'Ganglioneuroblastoma', label: 'Ganglioneuroblastoma'},
  {value: 'Gastric Bypass', label: 'Gastric Bypass'},
  {value: 'Gastric Dysmotility', label: 'Gastric Dysmotility'},
  {value: 'Gastritis', label: 'Gastritis'},
  {
    value: 'Gastroesophageal Reflux Disease (GERD)',
    label: 'Gastroesophageal Reflux Disease (GERD)',
  },
  {
    value: 'Gastrointestinal Stromal Tumor (GIST)',
    label: 'Gastrointestinal Stromal Tumor (GIST)',
  },
  {value: 'Gastroparesis (GP)', label: 'Gastroparesis (GP)'},
  {value: 'Gastroschisis', label: 'Gastroschisis'},
  {value: 'Gaucher Disease (GD)', label: 'Gaucher Disease (GD)'},
  {value: 'Gender Dysphoria', label: 'Gender Dysphoria'},
  {value: 'Giant Cell Arteritis (GCA)', label: 'Giant Cell Arteritis (GCA)'},
  {
    value: 'Glucose Transporter Deficiency (GLUT1DS)',
    label: 'Glucose Transporter Deficiency (GLUT1DS)',
  },
  {value: 'Gluten Intolerance', label: 'Gluten Intolerance'},
  {
    value: 'Glycogen Storage Disease (GSD)',
    label: 'Glycogen Storage Disease (GSD)',
  },
  {value: 'Goiter', label: 'Goiter'},
  {value: 'Goldenhar Syndrome', label: 'Goldenhar Syndrome'},
  {value: 'Gout', label: 'Gout'},
  {
    value: 'Graft Versus Host Disease (GVHD)',
    label: 'Graft Versus Host Disease (GVHD)',
  },
  {value: 'Granular Cell Tumors', label: 'Granular Cell Tumors'},
  {value: 'Granuloma Annulare (GA)', label: 'Granuloma Annulare (GA)'},
  {value: "Grave's Disease (GD)", label: "Grave's Disease (GD)"},
  {
    value: 'Guillain-Barre Syndrome (GBS)',
    label: 'Guillain-Barre Syndrome (GBS)',
  },
  {value: "Hansen's Disease (Leprosy)", label: "Hansen's Disease (Leprosy)"},
  {value: "Hashimoto's Disease (HT)", label: "Hashimoto's Disease (HT)"},
  {value: 'Head and Neck Cancer', label: 'Head and Neck Cancer'},
  {value: 'Headache', label: 'Headache'},
  {value: 'Hearing Aid', label: 'Hearing Aid'},
  {value: 'Hearing Loss', label: 'Hearing Loss'},
  {value: 'Heart Disease', label: 'Heart Disease'},
  {value: 'HELLP Syndrome', label: 'HELLP Syndrome'},
  {value: 'Hemangioma', label: 'Hemangioma'},
  {value: 'Hemihyperplasia', label: 'Hemihyperplasia'},
  {
    value: 'Hemochromatosis (Iron Overload)',
    label: 'Hemochromatosis (Iron Overload)',
  },
  {value: 'Hemophilia', label: 'Hemophilia'},
  {value: 'Hemorrhoids', label: 'Hemorrhoids'},
  {value: 'Hepatitis', label: 'Hepatitis'},
  {
    value: 'Hereditary alpha-tryptasemia (H?T)',
    label: 'Hereditary alpha-tryptasemia (H?T)',
  },
  {value: 'Hereditary Angioedema (HAE)', label: 'Hereditary Angioedema (HAE)'},
  {
    value: 'Hereditary hemorrhagic telangiectasia (HHT)',
    label: 'Hereditary hemorrhagic telangiectasia (HHT)',
  },
  {
    value: 'Hereditary Spastic Paraparesis (HSP)',
    label: 'Hereditary Spastic Paraparesis (HSP)',
  },
  {
    value: 'Hereditary Spastic Paraplegia (HSP)',
    label: 'Hereditary Spastic Paraplegia (HSP)',
  },
  {value: 'Hernia', label: 'Hernia'},
  {value: 'Herpes (HSV)', label: 'Herpes (HSV)'},
  {
    value: 'Hidradenitis Suppurativa (HS)',
    label: 'Hidradenitis Suppurativa (HS)',
  },
  {
    value: 'High Blood Pressure (Hypertensio, HBP)',
    label: 'High Blood Pressure (Hypertensio, HBP)',
  },
  {
    value: 'High Cholesterol (Hyperlipidemia)',
    label: 'High Cholesterol (Hyperlipidemia)',
  },
  {value: 'Hip Dysplasia', label: 'Hip Dysplasia'},
  {value: 'Hip Replacement', label: 'Hip Replacement'},
  {
    value: "Hirschsprung's Disease (H, HSCR)",
    label: "Hirschsprung's Disease (H, HSCR)",
  },
  {value: 'Hirsutism', label: 'Hirsutism'},
  {value: 'HIV', label: 'HIV'},
  {value: 'Hodgkins Lymphoma', label: 'Hodgkins Lymphoma'},
  {value: 'Holoprosencephaly (HPE)', label: 'Holoprosencephaly (HPE)'},
  {value: 'Homocystinuria (HCU)', label: 'Homocystinuria (HCU)'},
  {value: 'Horner Syndrome', label: 'Horner Syndrome'},
  {
    value: 'Human Growth Hormone Deficiency (GHD)',
    label: 'Human Growth Hormone Deficiency (GHD)',
  },
  {
    value: 'Human Papillomavirus (Human Papillomavirus (HPV)',
    label: 'Human Papillomavirus (Human Papillomavirus (HPV)',
  },
  {value: "Huntington's Disease (HD)", label: "Huntington's Disease (HD)"},
  {value: 'Hydrocephalus', label: 'Hydrocephalus'},
  {value: 'Hyper-IgA Syndrome', label: 'Hyper-IgA Syndrome'},
  {value: 'Hyperaldosteronism', label: 'Hyperaldosteronism'},
  {
    value: 'Hyperemesis Gravidarum (H, Morning Sickness)',
    label: 'Hyperemesis Gravidarum (H, Morning Sickness)',
  },
  {
    value: 'Hypereosinophilic Syndrome (HES)',
    label: 'Hypereosinophilic Syndrome (HES)',
  },
  {value: 'Hyperhidrosis', label: 'Hyperhidrosis'},
  {value: 'Hyperkalemia', label: 'Hyperkalemia'},
  {value: 'Hypermobility Syndrome', label: 'Hypermobility Syndrome'},
  {value: 'Hyperoxaluria', label: 'Hyperoxaluria'},
  {value: 'Hyperparathyroidism', label: 'Hyperparathyroidism'},
  {value: 'Hypersomnia', label: 'Hypersomnia'},
  {value: 'Hyperthyroidism', label: 'Hyperthyroidism'},
  {value: 'Hypocalcemia', label: 'Hypocalcemia'},
  {
    value: 'Hypoglycemia (Low Blood Sugar)',
    label: 'Hypoglycemia (Low Blood Sugar)',
  },
  {
    value: 'Hypohidrotic Ectodermal Dysplasia (HED)',
    label: 'Hypohidrotic Ectodermal Dysplasia (HED)',
  },
  {value: 'Hypokalemia', label: 'Hypokalemia'},
  {
    value: 'Hypokalemic Periodic Paralysis',
    label: 'Hypokalemic Periodic Paralysis',
  },
  {value: 'Hyponatremia', label: 'Hyponatremia'},
  {value: 'Hypoparathyroidism', label: 'Hypoparathyroidism'},
  {value: 'Hypophosphatasia (HPP)', label: 'Hypophosphatasia (HPP)'},
  {
    value: 'Hypoplasia of the Corpus Callosum',
    label: 'Hypoplasia of the Corpus Callosum',
  },
  {value: 'Hypothyroidism', label: 'Hypothyroidism'},
  {value: 'Hypotonia', label: 'Hypotonia'},
  {
    value: 'Hypoxic Ischemic Encephalopathy (HIE)',
    label: 'Hypoxic Ischemic Encephalopathy (HIE)',
  },
  {value: 'Hysterectomy', label: 'Hysterectomy'},
  {value: 'Ichthyosis', label: 'Ichthyosis'},
  {
    value: 'IgG 4 related disease (IgG4-RD)',
    label: 'IgG 4 related disease (IgG4-RD)',
  },
  {
    value: 'Immune Thrombocytopenic Purpura (ITP)',
    label: 'Immune Thrombocytopenic Purpura (ITP)',
  },
  {
    value:
      'Immunoglobulin Monoclonal Gammopathy of Undetermined Significance (IgM-MGUS)',
    label:
      'Immunoglobulin Monoclonal Gammopathy of Undetermined Significance (IgM-MGUS)',
  },
  {value: 'Incontinence', label: 'Incontinence'},
  {value: 'Incontinentia Pigmenti (IP)', label: 'Incontinentia Pigmenti (IP)'},
  {value: 'Infertility', label: 'Infertility'},
  {value: 'Insomnia', label: 'Insomnia'},
  {value: 'Intellectual Disability', label: 'Intellectual Disability'},
  {
    value: 'Intermittent Explosive Disorder (IED)',
    label: 'Intermittent Explosive Disorder (IED)',
  },
  {value: 'Interstitial Cystitis (IC)', label: 'Interstitial Cystitis (IC)'},
  {
    value: 'Interstitial Lung Disease (ILD)',
    label: 'Interstitial Lung Disease (ILD)',
  },
  {
    value: 'Intracranial Hemorrhage (Brain Bleeds)',
    label: 'Intracranial Hemorrhage (Brain Bleeds)',
  },
  {
    value: 'Intracranial Hypertension (I, Pseudotumor Cerebri)',
    label: 'Intracranial Hypertension (I, Pseudotumor Cerebri)',
  },
  {value: 'intracranial Pressure (ICP)', label: 'intracranial Pressure (ICP)'},
  {value: 'Iritis', label: 'Iritis'},
  {
    value: 'Irritable Bowel Syndrome (IBS)',
    label: 'Irritable Bowel Syndrome (IBS)',
  },
  {value: 'Ischemic Colitis', label: 'Ischemic Colitis'},
  {
    value: "Jansen's Metaphyseal Chondrodysplasia",
    label: "Jansen's Metaphyseal Chondrodysplasia",
  },
  {value: 'Juvenile Arthritis (JA)', label: 'Juvenile Arthritis (JA)'},
  {value: 'Kabuki Syndrome', label: 'Kabuki Syndrome'},
  {value: 'Kaposi Sarcoma (KS)', label: 'Kaposi Sarcoma (KS)'},
  {value: 'Kawasaki Disease', label: 'Kawasaki Disease'},
  {
    value: 'Keratosis Pilaris (follicular keratosis)',
    label: 'Keratosis Pilaris (follicular keratosis)',
  },
  {value: 'Kidney Disease', label: 'Kidney Disease'},
  {
    value: 'Klinefelter Syndrome (XXY Syndrome)',
    label: 'Klinefelter Syndrome (XXY Syndrome)',
  },
  {value: 'Klippel-Feil Syndrome (KFS)', label: 'Klippel-Feil Syndrome (KFS)'},
  {
    value: 'Klippel-Trenaunay Syndrome (KTS)',
    label: 'Klippel-Trenaunay Syndrome (KTS)',
  },
  {value: 'Knee Replacement', label: 'Knee Replacement'},
  {value: 'Lactose Intolerance', label: 'Lactose Intolerance'},
  {value: 'Lamb-Shaffer Syndrome', label: 'Lamb-Shaffer Syndrome'},
  {
    value: 'Lambert-Eaton myasthenic syndrome (LEMS)',
    label: 'Lambert-Eaton myasthenic syndrome (LEMS)',
  },
  {
    value: 'Landau Kleffner Syndrome (LKS)',
    label: 'Landau Kleffner Syndrome (LKS)',
  },
  {
    value: 'Langerhans Cell Histiocytosis (LCH)',
    label: 'Langerhans Cell Histiocytosis (LCH)',
  },
  {value: 'Larsen syndrome', label: 'Larsen syndrome'},
  {value: 'Laryngeal Cancer', label: 'Laryngeal Cancer'},
  {value: 'Laryngomalacia', label: 'Laryngomalacia'},
  {
    value: 'Laurence-Moon-Bardet-Biedl syndrome (LMBBS)',
    label: 'Laurence-Moon-Bardet-Biedl syndrome (LMBBS)',
  },
  {value: 'Learning Disability', label: 'Learning Disability'},
  {
    value: 'Legg-Calve-Perthes Disease (LCPD)',
    label: 'Legg-Calve-Perthes Disease (LCPD)',
  },
  {value: 'Leiomyosarcoma', label: 'Leiomyosarcoma'},
  {value: 'LEOPARD Syndrome', label: 'LEOPARD Syndrome'},
  {value: 'Leukemia', label: 'Leukemia'},
  {value: 'Leukocytosis', label: 'Leukocytosis'},
  {value: 'Leukodystrophy', label: 'Leukodystrophy'},
  {value: 'Leukopenia', label: 'Leukopenia'},
  {value: 'Lichen Planus', label: 'Lichen Planus'},
  {value: 'Lichen Sclerosis (LS)', label: 'Lichen Sclerosis (LS)'},
  {value: 'Lipedema', label: 'Lipedema'},
  {value: 'Lipodystrophy', label: 'Lipodystrophy'},
  {value: 'Liposarcoma', label: 'Liposarcoma'},
  {value: 'Lissencephaly', label: 'Lissencephaly'},
  {value: 'Livedo Reticularis (LR)', label: 'Livedo Reticularis (LR)'},
  {value: 'Liver Cancer', label: 'Liver Cancer'},
  {
    value: 'Liver Disease (not hepatitis)',
    label: 'Liver Disease (not hepatitis)',
  },
  {value: 'Loeys Dietz Syndrome', label: 'Loeys Dietz Syndrome'},
  {
    value: 'Loin Pain Hematuria Syndrome (LPHS)',
    label: 'Loin Pain Hematuria Syndrome (LPHS)',
  },
  {value: 'Loss of Mobility', label: 'Loss of Mobility'},
  {
    value: 'Low Blood Pressure (Hypotension)',
    label: 'Low Blood Pressure (Hypotension)',
  },
  {value: 'Low Testosterone', label: 'Low Testosterone'},
  {value: 'Lung Cancer', label: 'Lung Cancer'},
  {value: 'Lung Disease', label: 'Lung Disease'},
  {value: 'Lupus', label: 'Lupus'},
  {value: 'Lyme Disease', label: 'Lyme Disease'},
  {value: 'Lymphedema', label: 'Lymphedema'},
  {value: 'Lymphocytic Colitis', label: 'Lymphocytic Colitis'},
  {value: 'Lymphoma', label: 'Lymphoma'},
  {
    value: 'Lymphoproliferative Disease (LPD)',
    label: 'Lymphoproliferative Disease (LPD)',
  },
  {
    value: 'Lynch Syndrome (Hereditary Nonpolyposis Colorectal Cancer HNPCC)',
    label: 'Lynch Syndrome (Hereditary Nonpolyposis Colorectal Cancer HNPCC)',
  },
  {value: 'Macular Degeneration', label: 'Macular Degeneration'},
  {
    value: 'Macular Telangiectasia (MacTel)',
    label: 'Macular Telangiectasia (MacTel)',
  },
  {
    value: 'Mal de debarquement Syndrome (MdDS)',
    label: 'Mal de debarquement Syndrome (MdDS)',
  },
  {value: 'Malabsorption', label: 'Malabsorption'},
  {value: 'Malignant Hyperthermia (MH)', label: 'Malignant Hyperthermia (MH)'},
  {
    value: 'Maple Syrup Urine Disease (MSUD)',
    label: 'Maple Syrup Urine Disease (MSUD)',
  },
  {value: 'Marfan Syndrome (MFS)', label: 'Marfan Syndrome (MFS)'},
  {
    value: 'Mastocytosis (Mast Cell Activating Diseas, MCAD)',
    label: 'Mastocytosis (Mast Cell Activating Diseas, MCAD)',
  },
  {value: 'May Thurner Syndrome', label: 'May Thurner Syndrome'},
  {
    value: 'Mayer-Rokitansky-K ster-Hauser (MRKH) syndrome',
    label: 'Mayer-Rokitansky-K ster-Hauser (MRKH) syndrome',
  },
  {
    value: 'McCune-Albright Syndrome (MAS)',
    label: 'McCune-Albright Syndrome (MAS)',
  },
  {
    value: 'Median arcuate ligament syndrome (MALS)',
    label: 'Median arcuate ligament syndrome (MALS)',
  },
  {value: 'Memory Loss', label: 'Memory Loss'},
  {value: "Meniere's Disease (MD)", label: "Meniere's Disease (MD)"},
  {value: 'Menopause', label: 'Menopause'},
  {
    value: 'Menorrhagia (Heavy Menstrual Bleedin, Heavy Periods)',
    label: 'Menorrhagia (Heavy Menstrual Bleedin, Heavy Periods)',
  },
  {value: 'Mental Illness', label: 'Mental Illness'},
  {value: 'Mesothelioma', label: 'Mesothelioma'},
  {value: 'Metabolic Syndrome', label: 'Metabolic Syndrome'},
  {value: 'Metatarsalgia', label: 'Metatarsalgia'},
  {
    value: 'Methicillin-Resistant Staphylococcus Aureus (MRSA)',
    label: 'Methicillin-Resistant Staphylococcus Aureus (MRSA)',
  },
  {value: 'Microcephaly', label: 'Microcephaly'},
  {value: 'Microscopic Colitis', label: 'Microscopic Colitis'},
  {value: 'Microtia', label: 'Microtia'},
  {value: 'Migraine', label: 'Migraine'},
  {value: 'Mitochondrial Disease', label: 'Mitochondrial Disease'},
  {
    value: 'Mixed Connective Tissue Disease (MCTD)',
    label: 'Mixed Connective Tissue Disease (MCTD)',
  },
  {value: 'Moebius Syndrome', label: 'Moebius Syndrome'},
  {
    value: 'Monoclonal gammopathy of undetermined significance (MGUS)',
    label: 'Monoclonal gammopathy of undetermined significance (MGUS)',
  },
  {value: 'Mood Disorder', label: 'Mood Disorder'},
  {value: 'Morgellons Disease (MD)', label: 'Morgellons Disease (MD)'},
  {value: 'Moyamoya Disease', label: 'Moyamoya Disease'},
  {value: 'MTHFR', label: 'MTHFR'},
  {value: 'Mucopolysaccharidoses (MPS)', label: 'Mucopolysaccharidoses (MPS)'},
  {
    value: 'Multiple Endocrine Neoplasia (MEN)',
    label: 'Multiple Endocrine Neoplasia (MEN)',
  },
  {value: 'Multiple Myeloma (MM)', label: 'Multiple Myeloma (MM)'},
  {value: 'Multiple Sclerosis (MS)', label: 'Multiple Sclerosis (MS)'},
  {value: 'Multiple Scleros2is (MS)', label: 'Multiple Scleros2is (MS)'},
  {
    value: 'Multiple System Atrophy (MSA)',
    label: 'Multiple System Atrophy (MSA)',
  },
  {value: 'Muscle Spasms', label: 'Muscle Spasms'},
  {
    value: 'Muscle Tension Dysphonia (MTD)',
    label: 'Muscle Tension Dysphonia (MTD)',
  },
  {value: 'Muscular Dystrophy (MD)', label: 'Muscular Dystrophy (MD)'},
  {value: 'Myasthenia Gravis (MG)', label: 'Myasthenia Gravis (MG)'},
  {
    value: 'Mycobacterium Avium Complex (MAC)',
    label: 'Mycobacterium Avium Complex (MAC)',
  },
  {
    value:
      'Myelin oligodendrocyte glycoprotein Antibody-Associated Disease (MOG-Ab)',
    label:
      'Myelin oligodendrocyte glycoprotein Antibody-Associated Disease (MOG-Ab)',
  },
  {
    value: 'Myelodysplastic syndrome (MDS)',
    label: 'Myelodysplastic syndrome (MDS)',
  },
  {value: 'Myelofibrosis', label: 'Myelofibrosis'},
  {
    value: 'Myeloproliferative Neoplasms',
    label: 'Myeloproliferative Neoplasms',
  },
  {value: 'Myopathy', label: 'Myopathy'},
  {value: 'Myositis', label: 'Myositis'},
  {value: 'Narcolepsy', label: 'Narcolepsy'},
  {value: 'Nasal Polyps', label: 'Nasal Polyps'},
  {
    value: 'Nasopharyngeal Carcinoma (NPC)',
    label: 'Nasopharyngeal Carcinoma (NPC)',
  },
  {value: 'Neck Cancer', label: 'Neck Cancer'},
  {value: 'Neck Surgery', label: 'Neck Surgery'},
  {value: 'Neuralgia', label: 'Neuralgia'},
  {value: 'Neuroblastoma', label: 'Neuroblastoma'},
  {value: 'Neuroendocrine Cancer (NET)', label: 'Neuroendocrine Cancer (NET)'},
  {value: 'Neurofibromatosis (NF)', label: 'Neurofibromatosis (NF)'},
  {value: 'Neurogenic Bladder', label: 'Neurogenic Bladder'},
  {value: 'Neurogenic Bowel', label: 'Neurogenic Bowel'},
  {value: 'Neuromyelitis optica (NMO)', label: 'Neuromyelitis optica (NMO)'},
  {value: 'Neuropathy', label: 'Neuropathy'},
  {value: 'Neurotrophic Keratitis', label: 'Neurotrophic Keratitis'},
  {value: 'Neutropenia', label: 'Neutropenia'},
  {value: 'Niemann-Pick Disease', label: 'Niemann-Pick Disease'},
  {
    value: "Non-Hodgkin's Lymphoma (NHL)",
    label: "Non-Hodgkin's Lymphoma (NHL)",
  },
  {
    value: 'Non-radiographic Axial Spondyloarthritis (nrAxSpA)',
    label: 'Non-radiographic Axial Spondyloarthritis (nrAxSpA)',
  },
  {
    value: 'Nonspecific Interstitial Pneumonia (NSIP)',
    label: 'Nonspecific Interstitial Pneumonia (NSIP)',
  },
  {
    value: 'Nontuberculous Mycobacterial (NTM)',
    label: 'Nontuberculous Mycobacterial (NTM)',
  },
  {value: 'Noonan Syndrome (NS)', label: 'Noonan Syndrome (NS)'},
  {value: 'Obesity', label: 'Obesity'},
  {
    value: 'Obsessive Compulsive Disorder (OCD)',
    label: 'Obsessive Compulsive Disorder (OCD)',
  },
  {
    value: 'Oppositional Defiant Disorder (ODD)',
    label: 'Oppositional Defiant Disorder (ODD)',
  },
  {value: 'Oral Cancer', label: 'Oral Cancer'},
  {value: 'Organ Transplant', label: 'Organ Transplant'},
  {value: 'Organic Acidemia (OA)', label: 'Organic Acidemia (OA)'},
  {value: 'Osteoarthritis (OA)', label: 'Osteoarthritis (OA)'},
  {
    value: 'Osteogenesis Imperfecta (OI)',
    label: 'Osteogenesis Imperfecta (OI)',
  },
  {value: 'Osteomyelitis (OM)', label: 'Osteomyelitis (OM)'},
  {value: 'Osteopenia', label: 'Osteopenia'},
  {value: 'Osteoporosis', label: 'Osteoporosis'},
  {value: 'Ostomy', label: 'Ostomy'},
  {value: 'Ovarian Cancer', label: 'Ovarian Cancer'},
  {value: 'Ovarian Cyst', label: 'Ovarian Cyst'},
  {value: 'Overactive Bladder (OAB)', label: 'Overactive Bladder (OAB)'},
  {value: "Paget's", label: "Paget's"},
  {value: 'Palmoplantar Pustulosis', label: 'Palmoplantar Pustulosis'},
  {value: 'Pancreatic Cancer', label: 'Pancreatic Cancer'},
  {value: 'Pancreatitis', label: 'Pancreatitis'},
  {value: 'Paraganglioma', label: 'Paraganglioma'},
  {value: 'Paralysis', label: 'Paralysis'},
  {value: 'Paraneoplastic Syndrome', label: 'Paraneoplastic Syndrome'},
  {value: "Parkinson's Disease (PD)", label: "Parkinson's Disease (PD)"},
  {
    value: 'Paroxysmal Nocturnal Hemoglobinuria (PNH)',
    label: 'Paroxysmal Nocturnal Hemoglobinuria (PNH)',
  },
  {
    value:
      'Pediatric Autoimmune Neuropsychiatric Disorder Associated with Strep.(PANDAS)',
    label:
      'Pediatric Autoimmune Neuropsychiatric Disorder Associated with Strep.(PANDAS)',
  },
  {
    value: 'Pelvic Congestion Syndrome (PCS)',
    label: 'Pelvic Congestion Syndrome (PCS)',
  },
  {value: 'Pelvic Floor Dysfunction', label: 'Pelvic Floor Dysfunction'},
  {
    value: 'Pelvic Inflammatory Disease (PID)',
    label: 'Pelvic Inflammatory Disease (PID)',
  },
  {value: 'Pemphigus / Pemphigoid', label: 'Pemphigus / Pemphigoid'},
  {value: 'Pendred Syndrome', label: 'Pendred Syndrome'},
  {
    value: 'Periodic Limb Movement Disorder (PLMD)',
    label: 'Periodic Limb Movement Disorder (PLMD)',
  },
  {value: 'Periodontitis (Gum Disease)', label: 'Periodontitis (Gum Disease)'},
  {
    value: 'Perivascular Epithelioid Cell Tumour (PEComas)',
    label: 'Perivascular Epithelioid Cell Tumour (PEComas)',
  },
  {
    value: 'Periventricular Leukomalacia (PVL)',
    label: 'Periventricular Leukomalacia (PVL)',
  },
  {
    value: 'Persistent Genital Arousal Disorder',
    label: 'Persistent Genital Arousal Disorder',
  },
  {value: 'Personality Disorder', label: 'Personality Disorder'},
  {
    value: "Peyronie's Disease (Penile Fibrosis)",
    label: "Peyronie's Disease (Penile Fibrosis)",
  },
  {value: 'Pfeiffer Syndrome', label: 'Pfeiffer Syndrome'},
  {value: 'Phenylketonuria (PKU)', label: 'Phenylketonuria (PKU)'},
  {value: 'Pheochromocytoma (PCC)', label: 'Pheochromocytoma (PCC)'},
  {value: 'Pierre Robin Sequence (PRS)', label: 'Pierre Robin Sequence (PRS)'},
  {value: 'Pituitary Tumor', label: 'Pituitary Tumor'},
  {
    value: 'Plagiocephaly (Flat Head Syndrome)',
    label: 'Plagiocephaly (Flat Head Syndrome)',
  },
  {value: 'Plantar Fasciitis (PF)', label: 'Plantar Fasciitis (PF)'},
  {value: 'Pneumonia', label: 'Pneumonia'},
  {value: 'Poland Syndrome', label: 'Poland Syndrome'},
  {value: 'Polio', label: 'Polio'},
  {value: 'Polychrondritis', label: 'Polychrondritis'},
  {
    value: 'Polycystic Ovarian Syndrome (PCOS)',
    label: 'Polycystic Ovarian Syndrome (PCOS)',
  },
  {value: 'Polycythemia Vera (PV)', label: 'Polycythemia Vera (PV)'},
  {value: 'Polymicrogyria (PMG)', label: 'Polymicrogyria (PMG)'},
  {
    value: 'Polymyalgia Rheumatica (PMR)',
    label: 'Polymyalgia Rheumatica (PMR)',
  },
  {value: 'Polymyositis (PM)', label: 'Polymyositis (PM)'},
  {value: 'Pompe Disease', label: 'Pompe Disease'},
  {
    value: 'Popliteal Artery Entrapment Syndrome (PAES)',
    label: 'Popliteal Artery Entrapment Syndrome (PAES)',
  },
  {value: 'Porphyria', label: 'Porphyria'},
  {value: 'Post-Polio Syndrome (PPS)', label: 'Post-Polio Syndrome (PPS)'},
  {
    value: 'Posttraumatic Stress Disorder (PTSD)',
    label: 'Posttraumatic Stress Disorder (PTSD)',
  },
  {
    value: 'Pre-exposure Prophylaxis (PrEP)',
    label: 'Pre-exposure Prophylaxis (PrEP)',
  },
  {value: 'Precocious Puberty', label: 'Precocious Puberty'},
  {
    value:
      'Premature Ovarian Failure (POF) (Primary Ovarian Insufficiency POI)',
    label:
      'Premature Ovarian Failure (POF) (Primary Ovarian Insufficiency POI)',
  },
  {
    value: 'Premenstrual Dysphoric Disorder (PMDD)',
    label: 'Premenstrual Dysphoric Disorder (PMDD)',
  },
  {
    value: 'Primary Ciliary Dyskinesia (PCD)',
    label: 'Primary Ciliary Dyskinesia (PCD)',
  },
  {value: 'Primary Hyperoxaluria (PH)', label: 'Primary Hyperoxaluria (PH)'},
  {
    value: 'Primary Immunodeficiency (PID)',
    label: 'Primary Immunodeficiency (PID)',
  },
  {value: 'Primary Peritoneal', label: 'Primary Peritoneal'},
  {
    value: 'Progressive Multifocal Leukoencephalopathy (PML)',
    label: 'Progressive Multifocal Leukoencephalopathy (PML)',
  },
  {
    value: 'Progressive Supranuclear Palsy (PSP)',
    label: 'Progressive Supranuclear Palsy (PSP)',
  },
  {value: 'Prolactinoma', label: 'Prolactinoma'},
  {value: 'Prostate Cancer', label: 'Prostate Cancer'},
  {value: 'Protein Deficiency', label: 'Protein Deficiency'},
  {
    value: 'Proteinuria (Protein in Urine)',
    label: 'Proteinuria (Protein in Urine)',
  },
  {value: 'Prurigo Nodularis (PN)', label: 'Prurigo Nodularis (PN)'},
  {value: 'Pseudobulbar Affect (PBA)', label: 'Pseudobulbar Affect (PBA)'},
  {value: 'Psoriasis', label: 'Psoriasis'},
  {value: 'Psoriatic Arthritis (PsA)', label: 'Psoriatic Arthritis (PsA)'},
  {
    value: 'Ptosis (Drooping ey, Blepharoptosis)',
    label: 'Ptosis (Drooping ey, Blepharoptosis)',
  },
  {
    value: 'Pulmonary Arterial Hypertension (PAH)',
    label: 'Pulmonary Arterial Hypertension (PAH)',
  },
  {value: 'Pulmonary Embolism (PE)', label: 'Pulmonary Embolism (PE)'},
  {value: 'Pulmonary Fibrosis (PF)', label: 'Pulmonary Fibrosis (PF)'},
  {
    value: 'Pyloric Stenosis (Gastric Outlet Obstruction)',
    label: 'Pyloric Stenosis (Gastric Outlet Obstruction)',
  },
  {value: 'Pyoderma Gangrenosum (PG)', label: 'Pyoderma Gangrenosum (PG)'},
  {
    value: 'Pyruvate Kinase Deficiency (PKD)',
    label: 'Pyruvate Kinase Deficiency (PKD)',
  },
  {value: "Raynaud's Syndrome", label: "Raynaud's Syndrome"},
  {value: 'Rectal Cancer (CRC)', label: 'Rectal Cancer (CRC)'},
  {value: 'Rectocele', label: 'Rectocele'},
  {
    value: 'Renal Cell Carcinoma (Kidney Cance, RCC)',
    label: 'Renal Cell Carcinoma (Kidney Cance, RCC)',
  },
  {
    value: 'Respiratory Syncytial Virus (RSV) Infection',
    label: 'Respiratory Syncytial Virus (RSV) Infection',
  },
  {value: 'Restless Leg Syndrome (RLS)', label: 'Restless Leg Syndrome (RLS)'},
  {value: 'Retroperitoneal Fibrosis', label: 'Retroperitoneal Fibrosis'},
  {value: 'Rheumatoid Arthritis (RA)', label: 'Rheumatoid Arthritis (RA)'},
  {value: 'Rickets (Osteomalacia)', label: 'Rickets (Osteomalacia)'},
  {
    value: 'Rocky Mountain Spotted Fever (RMSF)',
    label: 'Rocky Mountain Spotted Fever (RMSF)',
  },
  {value: 'Rosacea', label: 'Rosacea'},
  {value: 'Rubella- German Measles', label: 'Rubella- German Measles'},
  {
    value: 'Sacroiliac Joint Disease (SI)',
    label: 'Sacroiliac Joint Disease (SI)',
  },
  {value: 'Sarcoidosis', label: 'Sarcoidosis'},
  {value: 'Sarcoma', label: 'Sarcoma'},
  {value: "Schamberg's Disease", label: "Schamberg's Disease"},
  {value: "Scheuermann's Kyphosis", label: "Scheuermann's Kyphosis"},
  {
    value: 'Schinzel-Giedion Syndrome (SGS)',
    label: 'Schinzel-Giedion Syndrome (SGS)',
  },
  {value: 'Schizencephaly', label: 'Schizencephaly'},
  {value: 'Schizophrenia', label: 'Schizophrenia'},
  {value: 'Sciatica', label: 'Sciatica'},
  {value: 'Scleroderma', label: 'Scleroderma'},
  {value: 'Sclerosing Peritonitis (SP)', label: 'Sclerosing Peritonitis (SP)'},
  {value: 'Scoliosis', label: 'Scoliosis'},
  {
    value: 'Secondary Adrenal insufficiency',
    label: 'Secondary Adrenal insufficiency',
  },
  {
    value: 'Sensory Processing Disorder (SPD)',
    label: 'Sensory Processing Disorder (SPD)',
  },
  {value: 'Sepsis', label: 'Sepsis'},
  {
    value: 'Sexually Transmitted Disease',
    label: 'Sexually Transmitted Disease',
  },
  {value: 'Shaken Baby Syndrome (SBS)', label: 'Shaken Baby Syndrome (SBS)'},
  {value: 'Shingles (Herpes Zoster)', label: 'Shingles (Herpes Zoster)'},
  {
    value: 'Short Bowel Syndrome (SB, Short Gut)',
    label: 'Short Bowel Syndrome (SB, Short Gut)',
  },
  {value: 'Shoulder Replacement', label: 'Shoulder Replacement'},
  {value: 'Sickle Cell Disease (SCD)', label: 'Sickle Cell Disease (SCD)'},
  {
    value: 'Sickle Cell Disease (SCD): Sickle Cell Trait',
    label: 'Sickle Cell Disease (SCD): Sickle Cell Trait',
  },
  {value: 'Sinusitis', label: 'Sinusitis'},
  {value: "Sjogren's Syndrome (Sj, SS)", label: "Sjogren's Syndrome (Sj, SS)"},
  {value: 'Skin Cancer', label: 'Skin Cancer'},
  {value: 'Skin Cancer- Melanoma', label: 'Skin Cancer- Melanoma'},
  {value: 'Sleep Apnea (OSA)', label: 'Sleep Apnea (OSA)'},
  {value: 'Sleep Disorder', label: 'Sleep Disorder'},
  {
    value: 'Small for Gestational Age SGA)',
    label: 'Small for Gestational Age SGA)',
  },
  {
    value: 'Small Intestinal Bacterial Overgrowth (SIBO)',
    label: 'Small Intestinal Bacterial Overgrowth (SIBO)',
  },
  {
    value: 'Smith-Lemli-Opitz Syndrome (SLOS)',
    label: 'Smith-Lemli-Opitz Syndrome (SLOS)',
  },
  {value: 'Sotos Syndrome', label: 'Sotos Syndrome'},
  {value: 'Spasmodic Dysphonia', label: 'Spasmodic Dysphonia'},
  {value: 'Spastic Diplegia', label: 'Spastic Diplegia'},
  {value: 'Spasticity', label: 'Spasticity'},
  {value: 'Speech Impairment', label: 'Speech Impairment'},
  {value: 'Spherocytosis', label: 'Spherocytosis'},
  {
    value: 'Sphincter of Oddi Dysfunction',
    label: 'Sphincter of Oddi Dysfunction',
  },
  {value: 'Spina Bifida (SB)', label: 'Spina Bifida (SB)'},
  {value: 'Spinal Cancer', label: 'Spinal Cancer'},
  {value: 'Spinal Cord', label: 'Spinal Cord'},
  {
    value: 'Spinal Muscular Atrophy (SMA)',
    label: 'Spinal Muscular Atrophy (SMA)',
  },
  {value: 'Sprengel Deformity', label: 'Sprengel Deformity'},
  {
    value: 'Squamous Cell Carcinoma (SCC)',
    label: 'Squamous Cell Carcinoma (SCC)',
  },
  {value: 'Stickler Syndrome', label: 'Stickler Syndrome'},
  {value: 'Stiff Person Syndrome (SPS)', label: 'Stiff Person Syndrome (SPS)'},
  {value: 'Stomach Cancer', label: 'Stomach Cancer'},
  {value: 'Stomach Ulcer', label: 'Stomach Ulcer'},
  {value: 'Stroke', label: 'Stroke'},
  {
    value: 'Subcortical Band Heterotopia',
    label: 'Subcortical Band Heterotopia',
  },
  {value: 'Subglottic Stenosis (SGS)', label: 'Subglottic Stenosis (SGS)'},
  {
    value: "Superior Mesenteric Artery Syndrome (SMA) (Wilkie's Syndrome)",
    label: "Superior Mesenteric Artery Syndrome (SMA) (Wilkie's Syndrome)",
  },
  {value: 'Syncope', label: 'Syncope'},
  {value: 'Synesthesia', label: 'Synesthesia'},
  {value: 'Syringomyelia', label: 'Syringomyelia'},
  {value: 'Tardive Dyskinesia (TD)', label: 'Tardive Dyskinesia (TD)'},
  {value: 'Tarlov Cysts', label: 'Tarlov Cysts'},
  {value: 'Tay Sachs (TSD)', label: 'Tay Sachs (TSD)'},
  {
    value: 'Temporomandibular joint (TMJ)',
    label: 'Temporomandibular joint (TMJ)',
  },
  {value: 'Tendonitis', label: 'Tendonitis'},
  {value: 'Testicular Cancer', label: 'Testicular Cancer'},
  {value: 'Thalassemia', label: 'Thalassemia'},
  {
    value: 'Thoracic Outlet Syndrome (TOS)',
    label: 'Thoracic Outlet Syndrome (TOS)',
  },
  {value: 'Throat Cancer', label: 'Throat Cancer'},
  {value: 'Thrombocytopenia (TCP)', label: 'Thrombocytopenia (TCP)'},
  {
    value: 'Thrombotic Thrombocytopenic Purpura (TTP)',
    label: 'Thrombotic Thrombocytopenic Purpura (TTP)',
  },
  {value: 'Thyroid Cancer', label: 'Thyroid Cancer'},
  {value: 'Thyroid Eye Disease (TED)', label: 'Thyroid Eye Disease (TED)'},
  {value: 'Thyroid Nodule', label: 'Thyroid Nodule'},
  {value: 'Thyroidectomy', label: 'Thyroidectomy'},
  {value: 'Tics', label: 'Tics'},
  {value: 'Tongue Cancer', label: 'Tongue Cancer'},
  {value: 'Tooth Agenesis (Anodontia)', label: 'Tooth Agenesis (Anodontia)'},
  {value: 'Torticollis (Wry Neck)', label: 'Torticollis (Wry Neck)'},
  {value: 'Tourette Syndrome (TS)', label: 'Tourette Syndrome (TS)'},
  {value: 'Townes-Brocks Syndrome', label: 'Townes-Brocks Syndrome'},
  {value: 'Toxic Synovitis', label: 'Toxic Synovitis'},
  {value: 'Tracheobronchomalacia (TBM)', label: 'Tracheobronchomalacia (TBM)'},
  {value: 'Tracheomalacia', label: 'Tracheomalacia'},
  {
    value: 'Transient Global Amnesia (TGA)',
    label: 'Transient Global Amnesia (TGA)',
  },
  {
    value: 'Traumatic Brain Injury (TBI)',
    label: 'Traumatic Brain Injury (TBI)',
  },
  {
    value: 'Treacher Collins syndrome (TCS)',
    label: 'Treacher Collins syndrome (TCS)',
  },
  {value: 'Trichotillomania (TTM)', label: 'Trichotillomania (TTM)'},
  {
    value: 'Trigger Finger (Stenosing Tenosynovitis)',
    label: 'Trigger Finger (Stenosing Tenosynovitis)',
  },
  {value: 'Trisomy 13 (Patau Syndrome)', label: 'Trisomy 13 (Patau Syndrome)'},
  {
    value: 'Trisomy 18 (Edwards Syndrome)',
    label: 'Trisomy 18 (Edwards Syndrome)',
  },
  {value: 'Trisomy X (XXX)', label: 'Trisomy X (XXX)'},
  {value: 'Tuberculosis', label: 'Tuberculosis'},
  {value: 'Ulcerative Colitis (UC)', label: 'Ulcerative Colitis (UC)'},
  {
    value: 'Undifferentiated Connective Tissue Disease (UCTD)',
    label: 'Undifferentiated Connective Tissue Disease (UCTD)',
  },
  {value: 'Urea Cycle Disorder (UCD)', label: 'Urea Cycle Disorder (UCD)'},
  {value: 'Urethral Prolapse', label: 'Urethral Prolapse'},
  {
    value: 'Urinary Tract Infection (UTI)',
    label: 'Urinary Tract Infection (UTI)',
  },
  {value: 'Urticaria (Hives)', label: 'Urticaria (Hives)'},
  {value: 'Usher Syndrome', label: 'Usher Syndrome'},
  {value: 'Uterine Cancer', label: 'Uterine Cancer'},
  {value: 'Uterine Fibroids', label: 'Uterine Fibroids'},
  {value: 'Uterine Leiomyosarcoma', label: 'Uterine Leiomyosarcoma'},
  {value: 'Uterine Polyps', label: 'Uterine Polyps'},
  {value: 'Uveitis', label: 'Uveitis'},
  {value: 'VACTERL Syndrome', label: 'VACTERL Syndrome'},
  {value: 'Vaginismus', label: 'Vaginismus'},
  {
    value: 'Valosin Containing Protein (VCP)',
    label: 'Valosin Containing Protein (VCP)',
  },
  {value: 'Varicose Veins', label: 'Varicose Veins'},
  {value: 'Vasculitis', label: 'Vasculitis'},
  {
    value: 'Velopharyngeal Insufficiency (VPI)',
    label: 'Velopharyngeal Insufficiency (VPI)',
  },
  {
    value: 'Vertebral Artery Dissection (VAD)',
    label: 'Vertebral Artery Dissection (VAD)',
  },
  {value: 'Vertigo', label: 'Vertigo'},
  {value: 'Vision Impairment', label: 'Vision Impairment'},
  {value: 'Vitamin B12 Deficiency', label: 'Vitamin B12 Deficiency'},
  {value: 'Vitamin D Deficiency', label: 'Vitamin D Deficiency'},
  {value: 'Vitiligo', label: 'Vitiligo'},
  {
    value: 'Vocal Cord Dysfunction (VCD)',
    label: 'Vocal Cord Dysfunction (VCD)',
  },
  {value: 'Von Hippel-Lindau Syndrome', label: 'Von Hippel-Lindau Syndrome'},
  {
    value: 'Von Willebrand Disease (VWD)',
    label: 'Von Willebrand Disease (VWD)',
  },
  {value: 'Vulvar Cancer', label: 'Vulvar Cancer'},
  {value: 'Vulvodynia', label: 'Vulvodynia'},
  {
    value: "Waldenstrom's Macroglobulinemia (W, Lymphoplasmacytic Lymphoma)",
    label: "Waldenstrom's Macroglobulinemia (W, Lymphoplasmacytic Lymphoma)",
  },
];

// Countries for form selection
export const countries = [
  {value: ' ', countryCode: 0, label: 'Select country'},
  {
    value: 'United States',
    countryCode: '+1',
    label: 'United States                                   ',
  },
  {value: 'Australia', countryCode: '+61', label: 'Australia'},
  {value: 'Canada', countryCode: '+1', label: 'Canada'},
  {value: 'United Kingdom', countryCode: '+44', label: 'United Kingdom'},
  {value: 'New Zealand', countryCode: '+64', label: 'New Zealand'},
];
